name: fluentzy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.4
  go_router: ^15.1.1
  flutter_svg: ^2.1.0
  lottie: ^3.3.1
  permission_handler: ^12.0.0
  flutter_tts: ^4.2.2
  speech_to_text: ^7.0.0
  google_generative_ai: ^0.4.7
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  http: ^1.3.0
  camera: ^0.11.1
  camera_web: ^0.3.5
  path_provider: ^2.1.5
  path: ^1.9.1
  image: ^4.5.4
  flutter_image_compress: ^2.4.0
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.6
  mime: ^2.0.0
  just_audio: ^0.10.2
  language_code: ^0.5.5
  flutter_slidable: ^4.0.0
  vibration: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
