// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaywMH77yxvL4n1-ARJbXp2nFbLy9gRlE',
    appId: '1:25664284579:web:1b1ff7cc708492e5021c16',
    messagingSenderId: '25664284579',
    projectId: 'fluentzy',
    authDomain: 'fluentzy.firebaseapp.com',
    storageBucket: 'fluentzy.firebasestorage.app',
    measurementId: 'G-CF01DQVH76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCRvfrrHtBuNEPBslBUhP30S6Tp5x1JHY',
    appId: '1:25664284579:android:f219f995d1412b21021c16',
    messagingSenderId: '25664284579',
    projectId: 'fluentzy',
    storageBucket: 'fluentzy.firebasestorage.app',
  );
}
